spring.application.name=backend-productos
# Puerto aplicacion
server.port=5000
# Conexion mock
external.product-service.base-url=${PRODUCT_SERVICE_URL:http://localhost:3001}
external.product-service.connect-timeout-ms=2000
external.product-service.read-timeout-ms=2000
# Actuator
management.endpoints.web.exposure.include=health,info